name: Rust Auto Publish
description: auto publish rust binary to github release
author: Aster <192607617@qq.com>
branding:
  icon: package
  color: orange
runs:
  using: node20
  main: rust-publish.js
env:
  GITHUB_TOKEN: Secret provided by github.com
  CRATES_TOKEN: Secret provided by crates.io
