name: 'Rust Auto Publish'
description: 'Auto publish rust binary to github release'
author: 'Aster <192607617@qq.com>'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'folder-plus'
  color: 'green'
inputs:
  wasm:
    description: 'Optional version of wasm-pack to install (eg. "v0.9.1", "latest")'
    required: false
    default: 'latest'
  trunk:
    description: 'Optional version of trunk to install (eg. "v0.6.0", "latest")'
    required: false
    default: 'latest'
outputs:
  DEPLOYMENT_STATUS:
    description: 'The status of the deployment that indicates if the run failed or passed. Possible outputs include: success|failed|skipped'
