package github:rust-release;

world action {
    variant github-error {
        custom(string)
    }
    enum github-target {
        all,
        github,
        npm,
        cargo,
    }
    export run-with-config: func(config: string, target: github-target) -> result<_, github-error>;
}
