[[github]]
path = "projects/publish-rs"
#bin = "all"
#bin = [selected]

[[crates]]
path = "projects/publish-rs"

[[npm]]
source = "projects/publish-rs"
path = "projects/publish-wasm32-wasi"
#bin = "only_one"
