name: Rust Auto Publish
description: Auto publish rust binary to github release
author: Aster <192607617@qq.com>
branding:
  icon: package
  color: orange
runs:
  using: node20
  main: rust-publish.js
env:
  GITHUB_TOKEN: As provided by Github Actions
inputs:
  github:
    description: Publish to github release
    required: false
    default: '{json}'
  crates:
    description: Publish to crates
    required: false
    default: '{json}'
  npm:
    description: Publish to npm
    required: false
    default: '{json}'
outputs:
  DEPLOYMENT_STATUS:
    description: 'The status of the deployment that indicates if the run failed or passed. Possible outputs include: success|failed|skipped'
